export const DELETE_MOVIE = "DELETE_MOVIE";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const UPDATE_DISLIKES = "UPDATE_DISLIKES";
export const SET_PAGE = "SET_PAGE";
export const SET_DISPLAY_LIMIT = "SET_DISPLAY_LIMIT";
export const SET_CATEGORY_FILTERS = "SET_CATEGORY_FILTERS";